name: Build

on: [push, pull_request]

jobs:
  build-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug
        ./waf.bat build

        

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: Source Engine
        path: D:\a\source-engine\source-engine\build\


